"""initial_schema

Revision ID: bb6ad5534a69
Revises: 
Create Date: 2026-03-28 08:06:40.866243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb6ad5534a69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('night_shifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('on_duty', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['on_duty'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('speaker_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('baby', 'dog', 'household', name='category_enum'), nullable=False),
    sa.Column('entry_type', sa.Enum('diary_entry', 'calendar_event', 'task', 'reminder', 'note', name='entry_type_enum'), nullable=False),
    sa.Column('raw_transcription', sa.Text(), nullable=False),
    sa.Column('language_detected', sa.String(length=5), nullable=True),
    sa.Column('extracted_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['speaker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baby_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('voice_entry_id', sa.Uuid(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('wake_time', sa.Time(), nullable=True),
    sa.Column('feed_time', sa.Time(), nullable=True),
    sa.Column('feed_type', sa.String(length=20), nullable=True),
    sa.Column('diaper_count', sa.Integer(), nullable=True),
    sa.Column('diaper_type', sa.String(length=20), nullable=True),
    sa.Column('sleep_time', sa.Time(), nullable=True),
    sa.Column('medication', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voice_entry_id'], ['voice_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('voice_entry_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('baby', 'dog', 'household', name='event_category_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['voice_entry_id'], ['voice_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dog_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('voice_entry_id', sa.Uuid(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.Enum('walk', 'feed', 'vet', 'grooming', 'medication', name='dog_activity_enum'), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('done_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['done_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voice_entry_id'], ['voice_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('voice_entry_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('pending', 'done', 'overdue', name='task_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voice_entry_id'], ['voice_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('household_tasks')
    op.drop_table('dog_logs')
    op.drop_table('calendar_events')
    op.drop_table('baby_logs')
    op.drop_table('voice_entries')
    op.drop_table('night_shifts')
    op.drop_table('users')
    # ### end Alembic commands ###
